backend:
  name: github
  branch: master
  repo: ChaituKNag/learn.thebestdeveloper.me

media_folder: src/images
public_folder: ../images
collections:
  - name: "trivia"
    label: "Trivia"
    folder: "src/content/trivia"
    create: true
    editor:
      preview: false
    slug: "{{year}}-{{month}}-{{day}}__{{topic}}__{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Topic", name: "topic", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string", default: "{{slug}}" }
      - { label: "Trivia Body", name: "body", widget: "markdown" }
